### ISSUE TITLE
images appearing twice

### ISSUE THREAD

**Issue by SpEcHiDe** [balasankarc/icu_diasposter#1]
I think the problem can be solved by scraping [this](http://chaluunion.com/rss) instead of [this](http://chaluunion.com)

**Comment by balasankarc** [comment]
The thing is, images appearing twice only happened recently. It was not there before, when I was running a cron job. Need to verify. Feel free to hack/dump-it-and-rewrite . As of now, I really don't have time to spend for this.

But there are other issues with the bot also. Something fishy going on with the underlying diaspy code. Images are being uploaded multiple times, but only one gets "public" bit set in the database. So, only one was displayed in the profile, but all copies were present in disk and DB, hence eating up space. Need to go through the original request/response code that does the job of uploading.
